#!/usr/bin/env python3
"""
Generate src/import_table.c from `nm -D --undefined-only libmain.so` output.

For every symbol the game library imports:
  1. if src/*.c defines ov_<symbol>   -> bind to our compatibility wrapper
  2. elif it is SDL_* / C++ ABI / a known-safe libc function -> bind to the host symbol
  3. else -> reported as UNKNOWN (bound to a stub that logs and aborts at runtime)

usage: gen_import_table.py imports.txt src/import_table.c
"""
import re, sys, glob, os

HOST_EXACT = set("""
abort exit calloc malloc free realloc memchr memcmp memcpy memmove memset
strcasecmp strcat strchr strcmp strcpy strlen strncasecmp strncmp strncpy strsep strtok strerror
atoi atol qsort rand srand div getenv setjmp longjmp setlocale localeconv
strtol strtoll strtoul strtoull sscanf vsscanf vsnprintf snprintf vasprintf
btowc wctob mbrlen mbrtowc mbsnrtowcs mbsrtowcs mbtowc wcrtomb wcslen wcsnrtombs
wmemchr wmemcmp wcstol wcstoll wcstoul wcstoull swprintf
write __cxa_atexit __cxa_finalize
""".split())
HOST_PREFIX = ("_Z", "__cxa_", "__dynamic_cast", "__gxx_personality_v0", "SDL_")
ALIAS = {"sigsetjmp": "setjmp", "siglongjmp": "longjmp"}
DATA_PREFIX = ("_ZT",)          # typeinfo / vtables are data objects

src_dir = os.path.join(os.path.dirname(os.path.abspath(sys.argv[2])))
ov = set()
for f in glob.glob(os.path.join(src_dir, "*.c")):
    if f.endswith("import_table.c"): continue
    for m in re.finditer(r'\bov_([A-Za-z0-9_]+)\b\s*(?:\(|\[|=|;)', open(f).read()):
        ov.add(m.group(1))
# macro-generated wrappers (F1/D1/ISW/STUB_*)
for f in glob.glob(os.path.join(src_dir, "*.c")):
    t = open(f).read()
    for m in re.finditer(r'\b(?:F1|D1|ISW|STUB_NEG|STUB_NIL|STUB_OK)\(([^)]*)\)', t):
        pass
    for mac, fmt in (("F1","{}"),("D1","{}"),("ISW","{}_l"),("STUB_NEG","{}"),("STUB_NIL","{}"),("STUB_OK","{}")):
        for m in re.finditer(r'\b%s\(([A-Za-z0-9_]+)\)' % mac, t):
            ov.add(fmt.format(m.group(1)))

names = []
for line in open(sys.argv[1]):
    p = line.split()
    if len(p) >= 2 and p[-2] == "U":
        names.append(p[-1].split("@")[0])
names = sorted(set(names))

rows, decls, unknown = [], [], []
for n in names:
    if n in ov:
        sym = "ov_" + n
    elif n in ALIAS:
        sym = ALIAS[n]
    elif n in HOST_EXACT or n.startswith(HOST_PREFIX):
        sym = n
    else:
        unknown.append(n); continue
    if sym.startswith(DATA_PREFIX) or sym in ("ov___sF", "ov___stack_chk_guard"):
        decls.append("extern char %s[];" % sym); rows.append('    { "%s", (uintptr_t)%s },' % (n, sym))
    else:
        decls.append("extern void %s(void);" % sym); rows.append('    { "%s", (uintptr_t)&%s },' % (n, sym))

with open(sys.argv[2], "w") as o:
    o.write("/* AUTO-GENERATED by tools/gen_import_table.py - do not edit */\n")
    o.write("#pragma GCC diagnostic ignored \"-Wbuiltin-declaration-mismatch\"\n#include <stdint.h>\n#include <stddef.h>\n#include \"so_util.h\"\n\n")
    o.write("\n".join(sorted(set(decls))) + "\n\n")
    o.write("const SoImport g_imports[] = {\n" + "\n".join(rows) + "\n};\n")
    o.write("const size_t g_imports_count = sizeof g_imports / sizeof g_imports[0];\n")

print("%d imports: %d bound, %d unknown" % (len(names), len(rows), len(unknown)))
for n in unknown: print("  UNKNOWN:", n)
sys.exit(1 if unknown else 0)
