/* AUTO-GENERATED by tools/gen_import_table.py - do not edit */
#pragma GCC diagnostic ignored "-Wbuiltin-declaration-mismatch"
#include <stdint.h>
#include <stddef.h>
#include "so_util.h"

extern char _ZTISt20bad_array_new_length[];
extern char _ZTISt8bad_cast[];
extern char _ZTISt9bad_alloc[];
extern char _ZTISt9exception[];
extern char _ZTVN10__cxxabiv117__class_type_infoE[];
extern char _ZTVN10__cxxabiv120__si_class_type_infoE[];
extern char _ZTVN10__cxxabiv121__vmi_class_type_infoE[];
extern char ov___sF[];
extern char ov___stack_chk_guard[];
extern void SDL_AtomicGet(void);
extern void SDL_AtomicSet(void);
extern void SDL_AudioStreamClear(void);
extern void SDL_AudioStreamFlush(void);
extern void SDL_AudioStreamGet(void);
extern void SDL_AudioStreamPut(void);
extern void SDL_BuildAudioCVT(void);
extern void SDL_ClearError(void);
extern void SDL_CloseAudioDevice(void);
extern void SDL_ConvertAudio(void);
extern void SDL_CreateColorCursor(void);
extern void SDL_CreateRGBSurfaceWithFormat(void);
extern void SDL_CreateSystemCursor(void);
extern void SDL_CreateThreadWithStackSize(void);
extern void SDL_Delay(void);
extern void SDL_DestroyWindow(void);
extern void SDL_Error(void);
extern void SDL_FreeAudioStream(void);
extern void SDL_FreeCursor(void);
extern void SDL_FreeSurface(void);
extern void SDL_GL_GetDrawableSize(void);
extern void SDL_GL_SetSwapInterval(void);
extern void SDL_GetClipboardText(void);
extern void SDL_GetError(void);
extern void SDL_GetHintBoolean(void);
extern void SDL_GetPerformanceCounter(void);
extern void SDL_GetPerformanceFrequency(void);
extern void SDL_GetTicks(void);
extern void SDL_GetWindowFlags(void);
extern void SDL_HasEvents(void);
extern void SDL_Init(void);
extern void SDL_InitSubSystem(void);
extern void SDL_IsTextInputActive(void);
extern void SDL_LoadFile_RW(void);
extern void SDL_LoadWAV_RW(void);
extern void SDL_LockAudioDevice(void);
extern void SDL_MixAudioFormat(void);
extern void SDL_NewAudioStream(void);
extern void SDL_NumJoysticks(void);
extern void SDL_OpenAudioDevice(void);
extern void SDL_PauseAudioDevice(void);
extern void SDL_PumpEvents(void);
extern void SDL_Quit(void);
extern void SDL_QuitSubSystem(void);
extern void SDL_RWFromConstMem(void);
extern void SDL_RWclose(void);
extern void SDL_RWread(void);
extern void SDL_RWseek(void);
extern void SDL_RWsize(void);
extern void SDL_RWtell(void);
extern void SDL_ReadBE16(void);
extern void SDL_ReadBE32(void);
extern void SDL_ReadLE32(void);
extern void SDL_SetClipboardText(void);
extern void SDL_SetCursor(void);
extern void SDL_SetError(void);
extern void SDL_SetHint(void);
extern void SDL_SetWindowFullscreen(void);
extern void SDL_ShowCursor(void);
extern void SDL_StartTextInput(void);
extern void SDL_StopTextInput(void);
extern void SDL_UnlockAudioDevice(void);
extern void SDL_WaitThread(void);
extern void SDL_WasInit(void);
extern void SDL_atoi(void);
extern void SDL_calloc(void);
extern void SDL_free(void);
extern void SDL_getenv(void);
extern void SDL_iconv_string(void);
extern void SDL_isdigit(void);
extern void SDL_malloc(void);
extern void SDL_memcmp(void);
extern void SDL_memcpy(void);
extern void SDL_memmove(void);
extern void SDL_memset(void);
extern void SDL_realloc(void);
extern void SDL_snprintf(void);
extern void SDL_strcasecmp(void);
extern void SDL_strchr(void);
extern void SDL_strcmp(void);
extern void SDL_strdup(void);
extern void SDL_strlcpy(void);
extern void SDL_strlen(void);
extern void SDL_strncasecmp(void);
extern void SDL_strncmp(void);
extern void SDL_strrchr(void);
extern void SDL_strtokr(void);
extern void SDL_strtol(void);
extern void SDL_strtoll(void);
extern void _ZNKSt9exception4whatEv(void);
extern void _ZNSt20bad_array_new_lengthD1Ev(void);
extern void _ZNSt8bad_castD1Ev(void);
extern void _ZNSt9bad_allocD1Ev(void);
extern void _ZNSt9exceptionD2Ev(void);
extern void _ZSt9terminatev(void);
extern void _ZdaPv(void);
extern void _ZdaPvj(void);
extern void _ZdlPv(void);
extern void _ZdlPvRKSt9nothrow_t(void);
extern void _ZdlPvj(void);
extern void __cxa_allocate_exception(void);
extern void __cxa_atexit(void);
extern void __cxa_begin_catch(void);
extern void __cxa_end_catch(void);
extern void __cxa_end_cleanup(void);
extern void __cxa_finalize(void);
extern void __cxa_free_exception(void);
extern void __cxa_init_primary_exception(void);
extern void __cxa_pure_virtual(void);
extern void __cxa_rethrow(void);
extern void __cxa_throw(void);
extern void __dynamic_cast(void);
extern void __gxx_personality_v0(void);
extern void atoi(void);
extern void atol(void);
extern void btowc(void);
extern void calloc(void);
extern void div(void);
extern void free(void);
extern void getenv(void);
extern void localeconv(void);
extern void longjmp(void);
extern void mbrlen(void);
extern void mbrtowc(void);
extern void mbsnrtowcs(void);
extern void mbsrtowcs(void);
extern void mbtowc(void);
extern void memchr(void);
extern void memcmp(void);
extern void memcpy(void);
extern void memmove(void);
extern void memset(void);
extern void ov_SDL_AndroidGetExternalStoragePath(void);
extern void ov_SDL_CreateWindow(void);
extern void ov_SDL_GL_CreateContext(void);
extern void ov_SDL_GL_GetProcAddress(void);
extern void ov_SDL_GL_SetAttribute(void);
extern void ov_SDL_GL_SwapWindow(void);
extern void ov_SDL_Log(void);
extern void ov_SDL_PollEvent(void);
extern void ov_SDL_RWFromFile(void);
extern void ov_SDL_ShowSimpleMessageBox(void);
extern void ov_SDL_atof(void);
extern void ov__ZNSt20bad_array_new_lengthC1Ev(void);
extern void ov__ZNSt8bad_castC1Ev(void);
extern void ov__ZNSt9bad_allocC1Ev(void);
extern void ov__Znaj(void);
extern void ov__ZnajRKSt9nothrow_t(void);
extern void ov__Znwj(void);
extern void ov__ZnwjRKSt9nothrow_t(void);
extern void ov___android_log_write(void);
extern void ov___ctype_get_mb_cur_max(void);
extern void ov___cxa_current_primary_exception(void);
extern void ov___cxa_decrement_exception_refcount(void);
extern void ov___cxa_increment_exception_refcount(void);
extern void ov___cxa_rethrow_primary_exception(void);
extern void ov___cxa_uncaught_exceptions(void);
extern void ov___emutls_get_address(void);
extern void ov___errno(void);
extern void ov___memcpy_chk(void);
extern void ov___read_chk(void);
extern void ov___stack_chk_fail(void);
extern void ov___strcat_chk(void);
extern void ov___strchr_chk(void);
extern void ov___strcpy_chk(void);
extern void ov___strlen_chk(void);
extern void ov___strncpy_chk(void);
extern void ov___vsnprintf_chk(void);
extern void ov___vsprintf_chk(void);
extern void ov_abort(void);
extern void ov_acos(void);
extern void ov_android_set_abort_message(void);
extern void ov_asctime(void);
extern void ov_atan(void);
extern void ov_atof(void);
extern void ov_ceil(void);
extern void ov_ceilf(void);
extern void ov_chdir(void);
extern void ov_clock_gettime(void);
extern void ov_close(void);
extern void ov_closedir(void);
extern void ov_closelog(void);
extern void ov_cos(void);
extern void ov_cosf(void);
extern void ov_exit(void);
extern void ov_exp(void);
extern void ov_exp2(void);
extern void ov_exp2f(void);
extern void ov_fchmod(void);
extern void ov_fchmodat(void);
extern void ov_fclose(void);
extern void ov_fdopen(void);
extern void ov_fdopendir(void);
extern void ov_feof(void);
extern void ov_ferror(void);
extern void ov_fflush(void);
extern void ov_fgetc(void);
extern void ov_fgets(void);
extern void ov_floor(void);
extern void ov_floorf(void);
extern void ov_fopen(void);
extern void ov_fprintf(void);
extern void ov_fputc(void);
extern void ov_fputs(void);
extern void ov_fputwc(void);
extern void ov_fread(void);
extern void ov_freelocale(void);
extern void ov_frexp(void);
extern void ov_fscanf(void);
extern void ov_fseek(void);
extern void ov_fseeko(void);
extern void ov_fstat(void);
extern void ov_ftell(void);
extern void ov_ftello(void);
extern void ov_ftruncate(void);
extern void ov_fwrite(void);
extern void ov_getc(void);
extern void ov_getcwd(void);
extern void ov_getwc(void);
extern void ov_gmtime(void);
extern void ov_hypot(void);
extern void ov_ioctl(void);
extern void ov_iswalpha_l(void);
extern void ov_iswblank_l(void);
extern void ov_iswcntrl_l(void);
extern void ov_iswdigit_l(void);
extern void ov_iswlower_l(void);
extern void ov_iswprint_l(void);
extern void ov_iswpunct_l(void);
extern void ov_iswspace_l(void);
extern void ov_iswupper_l(void);
extern void ov_iswxdigit_l(void);
extern void ov_ldexp(void);
extern void ov_link(void);
extern void ov_localtime64_r(void);
extern void ov_log(void);
extern void ov_log10(void);
extern void ov_log10f(void);
extern void ov_log2(void);
extern void ov_logf(void);
extern void ov_lseek(void);
extern void ov_lseek64(void);
extern void ov_lstat(void);
extern void ov_malloc(void);
extern void ov_mkdir(void);
extern void ov_modf(void);
extern void ov_nanosleep(void);
extern void ov_newlocale(void);
extern void ov_open(void);
extern void ov_openat(void);
extern void ov_opendir(void);
extern void ov_openlog(void);
extern void ov_pathconf(void);
extern void ov_pow(void);
extern void ov_powf(void);
extern void ov_pthread_cond_broadcast(void);
extern void ov_pthread_cond_destroy(void);
extern void ov_pthread_cond_signal(void);
extern void ov_pthread_cond_timedwait(void);
extern void ov_pthread_cond_wait(void);
extern void ov_pthread_create(void);
extern void ov_pthread_detach(void);
extern void ov_pthread_getspecific(void);
extern void ov_pthread_join(void);
extern void ov_pthread_key_create(void);
extern void ov_pthread_mutex_destroy(void);
extern void ov_pthread_mutex_init(void);
extern void ov_pthread_mutex_lock(void);
extern void ov_pthread_mutex_trylock(void);
extern void ov_pthread_mutex_unlock(void);
extern void ov_pthread_mutexattr_destroy(void);
extern void ov_pthread_mutexattr_init(void);
extern void ov_pthread_mutexattr_settype(void);
extern void ov_pthread_self(void);
extern void ov_pthread_setspecific(void);
extern void ov_read(void);
extern void ov_readdir(void);
extern void ov_readlink(void);
extern void ov_realpath(void);
extern void ov_remove(void);
extern void ov_rename(void);
extern void ov_rint(void);
extern void ov_rintf(void);
extern void ov_round(void);
extern void ov_roundf(void);
extern void ov_sendfile(void);
extern void ov_setbuf(void);
extern void ov_sigaction(void);
extern void ov_sigemptyset(void);
extern void ov_sin(void);
extern void ov_sincos(void);
extern void ov_sincosf(void);
extern void ov_sinf(void);
extern void ov_sinhf(void);
extern void ov_stat(void);
extern void ov_statvfs(void);
extern void ov_strcoll_l(void);
extern void ov_strerror_r(void);
extern void ov_strftime(void);
extern void ov_strftime_l(void);
extern void ov_strtod(void);
extern void ov_strtof(void);
extern void ov_strtold(void);
extern void ov_strtold_l(void);
extern void ov_strtoll_l(void);
extern void ov_strtoull_l(void);
extern void ov_strxfrm_l(void);
extern void ov_symlink(void);
extern void ov_sysconf(void);
extern void ov_syslog(void);
extern void ov_tan(void);
extern void ov_tanf(void);
extern void ov_towlower_l(void);
extern void ov_towupper_l(void);
extern void ov_truncate(void);
extern void ov_ungetc(void);
extern void ov_ungetwc(void);
extern void ov_unlinkat(void);
extern void ov_uselocale(void);
extern void ov_utimensat(void);
extern void ov_vfprintf(void);
extern void ov_wcscoll_l(void);
extern void ov_wcstod(void);
extern void ov_wcstof(void);
extern void ov_wcstold(void);
extern void ov_wcsxfrm_l(void);
extern void qsort(void);
extern void rand(void);
extern void realloc(void);
extern void setjmp(void);
extern void setlocale(void);
extern void snprintf(void);
extern void srand(void);
extern void sscanf(void);
extern void strcasecmp(void);
extern void strcat(void);
extern void strchr(void);
extern void strcmp(void);
extern void strcpy(void);
extern void strerror(void);
extern void strlen(void);
extern void strncasecmp(void);
extern void strncmp(void);
extern void strncpy(void);
extern void strsep(void);
extern void strtok(void);
extern void strtol(void);
extern void strtoll(void);
extern void strtoul(void);
extern void strtoull(void);
extern void swprintf(void);
extern void vasprintf(void);
extern void vsnprintf(void);
extern void vsscanf(void);
extern void wcrtomb(void);
extern void wcslen(void);
extern void wcsnrtombs(void);
extern void wcstol(void);
extern void wcstoll(void);
extern void wcstoul(void);
extern void wcstoull(void);
extern void wctob(void);
extern void wmemchr(void);
extern void wmemcmp(void);
extern void write(void);

const SoImport g_imports[] = {
    { "SDL_AndroidGetExternalStoragePath", (uintptr_t)&ov_SDL_AndroidGetExternalStoragePath },
    { "SDL_AtomicGet", (uintptr_t)&SDL_AtomicGet },
    { "SDL_AtomicSet", (uintptr_t)&SDL_AtomicSet },
    { "SDL_AudioStreamClear", (uintptr_t)&SDL_AudioStreamClear },
    { "SDL_AudioStreamFlush", (uintptr_t)&SDL_AudioStreamFlush },
    { "SDL_AudioStreamGet", (uintptr_t)&SDL_AudioStreamGet },
    { "SDL_AudioStreamPut", (uintptr_t)&SDL_AudioStreamPut },
    { "SDL_BuildAudioCVT", (uintptr_t)&SDL_BuildAudioCVT },
    { "SDL_ClearError", (uintptr_t)&SDL_ClearError },
    { "SDL_CloseAudioDevice", (uintptr_t)&SDL_CloseAudioDevice },
    { "SDL_ConvertAudio", (uintptr_t)&SDL_ConvertAudio },
    { "SDL_CreateColorCursor", (uintptr_t)&SDL_CreateColorCursor },
    { "SDL_CreateRGBSurfaceWithFormat", (uintptr_t)&SDL_CreateRGBSurfaceWithFormat },
    { "SDL_CreateSystemCursor", (uintptr_t)&SDL_CreateSystemCursor },
    { "SDL_CreateThreadWithStackSize", (uintptr_t)&SDL_CreateThreadWithStackSize },
    { "SDL_CreateWindow", (uintptr_t)&ov_SDL_CreateWindow },
    { "SDL_Delay", (uintptr_t)&SDL_Delay },
    { "SDL_DestroyWindow", (uintptr_t)&SDL_DestroyWindow },
    { "SDL_Error", (uintptr_t)&SDL_Error },
    { "SDL_FreeAudioStream", (uintptr_t)&SDL_FreeAudioStream },
    { "SDL_FreeCursor", (uintptr_t)&SDL_FreeCursor },
    { "SDL_FreeSurface", (uintptr_t)&SDL_FreeSurface },
    { "SDL_GL_CreateContext", (uintptr_t)&ov_SDL_GL_CreateContext },
    { "SDL_GL_GetDrawableSize", (uintptr_t)&SDL_GL_GetDrawableSize },
    { "SDL_GL_GetProcAddress", (uintptr_t)&ov_SDL_GL_GetProcAddress },
    { "SDL_GL_SetAttribute", (uintptr_t)&ov_SDL_GL_SetAttribute },
    { "SDL_GL_SetSwapInterval", (uintptr_t)&SDL_GL_SetSwapInterval },
    { "SDL_GL_SwapWindow", (uintptr_t)&ov_SDL_GL_SwapWindow },
    { "SDL_GetClipboardText", (uintptr_t)&SDL_GetClipboardText },
    { "SDL_GetError", (uintptr_t)&SDL_GetError },
    { "SDL_GetHintBoolean", (uintptr_t)&SDL_GetHintBoolean },
    { "SDL_GetPerformanceCounter", (uintptr_t)&SDL_GetPerformanceCounter },
    { "SDL_GetPerformanceFrequency", (uintptr_t)&SDL_GetPerformanceFrequency },
    { "SDL_GetTicks", (uintptr_t)&SDL_GetTicks },
    { "SDL_GetWindowFlags", (uintptr_t)&SDL_GetWindowFlags },
    { "SDL_HasEvents", (uintptr_t)&SDL_HasEvents },
    { "SDL_Init", (uintptr_t)&SDL_Init },
    { "SDL_InitSubSystem", (uintptr_t)&SDL_InitSubSystem },
    { "SDL_IsTextInputActive", (uintptr_t)&SDL_IsTextInputActive },
    { "SDL_LoadFile_RW", (uintptr_t)&SDL_LoadFile_RW },
    { "SDL_LoadWAV_RW", (uintptr_t)&SDL_LoadWAV_RW },
    { "SDL_LockAudioDevice", (uintptr_t)&SDL_LockAudioDevice },
    { "SDL_Log", (uintptr_t)&ov_SDL_Log },
    { "SDL_MixAudioFormat", (uintptr_t)&SDL_MixAudioFormat },
    { "SDL_NewAudioStream", (uintptr_t)&SDL_NewAudioStream },
    { "SDL_NumJoysticks", (uintptr_t)&SDL_NumJoysticks },
    { "SDL_OpenAudioDevice", (uintptr_t)&SDL_OpenAudioDevice },
    { "SDL_PauseAudioDevice", (uintptr_t)&SDL_PauseAudioDevice },
    { "SDL_PollEvent", (uintptr_t)&ov_SDL_PollEvent },
    { "SDL_PumpEvents", (uintptr_t)&SDL_PumpEvents },
    { "SDL_Quit", (uintptr_t)&SDL_Quit },
    { "SDL_QuitSubSystem", (uintptr_t)&SDL_QuitSubSystem },
    { "SDL_RWFromConstMem", (uintptr_t)&SDL_RWFromConstMem },
    { "SDL_RWFromFile", (uintptr_t)&ov_SDL_RWFromFile },
    { "SDL_RWclose", (uintptr_t)&SDL_RWclose },
    { "SDL_RWread", (uintptr_t)&SDL_RWread },
    { "SDL_RWseek", (uintptr_t)&SDL_RWseek },
    { "SDL_RWsize", (uintptr_t)&SDL_RWsize },
    { "SDL_RWtell", (uintptr_t)&SDL_RWtell },
    { "SDL_ReadBE16", (uintptr_t)&SDL_ReadBE16 },
    { "SDL_ReadBE32", (uintptr_t)&SDL_ReadBE32 },
    { "SDL_ReadLE32", (uintptr_t)&SDL_ReadLE32 },
    { "SDL_SetClipboardText", (uintptr_t)&SDL_SetClipboardText },
    { "SDL_SetCursor", (uintptr_t)&SDL_SetCursor },
    { "SDL_SetError", (uintptr_t)&SDL_SetError },
    { "SDL_SetHint", (uintptr_t)&SDL_SetHint },
    { "SDL_SetWindowFullscreen", (uintptr_t)&SDL_SetWindowFullscreen },
    { "SDL_ShowCursor", (uintptr_t)&SDL_ShowCursor },
    { "SDL_ShowSimpleMessageBox", (uintptr_t)&ov_SDL_ShowSimpleMessageBox },
    { "SDL_StartTextInput", (uintptr_t)&SDL_StartTextInput },
    { "SDL_StopTextInput", (uintptr_t)&SDL_StopTextInput },
    { "SDL_UnlockAudioDevice", (uintptr_t)&SDL_UnlockAudioDevice },
    { "SDL_WaitThread", (uintptr_t)&SDL_WaitThread },
    { "SDL_WasInit", (uintptr_t)&SDL_WasInit },
    { "SDL_atof", (uintptr_t)&ov_SDL_atof },
    { "SDL_atoi", (uintptr_t)&SDL_atoi },
    { "SDL_calloc", (uintptr_t)&SDL_calloc },
    { "SDL_free", (uintptr_t)&SDL_free },
    { "SDL_getenv", (uintptr_t)&SDL_getenv },
    { "SDL_iconv_string", (uintptr_t)&SDL_iconv_string },
    { "SDL_isdigit", (uintptr_t)&SDL_isdigit },
    { "SDL_malloc", (uintptr_t)&SDL_malloc },
    { "SDL_memcmp", (uintptr_t)&SDL_memcmp },
    { "SDL_memcpy", (uintptr_t)&SDL_memcpy },
    { "SDL_memmove", (uintptr_t)&SDL_memmove },
    { "SDL_memset", (uintptr_t)&SDL_memset },
    { "SDL_realloc", (uintptr_t)&SDL_realloc },
    { "SDL_snprintf", (uintptr_t)&SDL_snprintf },
    { "SDL_strcasecmp", (uintptr_t)&SDL_strcasecmp },
    { "SDL_strchr", (uintptr_t)&SDL_strchr },
    { "SDL_strcmp", (uintptr_t)&SDL_strcmp },
    { "SDL_strdup", (uintptr_t)&SDL_strdup },
    { "SDL_strlcpy", (uintptr_t)&SDL_strlcpy },
    { "SDL_strlen", (uintptr_t)&SDL_strlen },
    { "SDL_strncasecmp", (uintptr_t)&SDL_strncasecmp },
    { "SDL_strncmp", (uintptr_t)&SDL_strncmp },
    { "SDL_strrchr", (uintptr_t)&SDL_strrchr },
    { "SDL_strtokr", (uintptr_t)&SDL_strtokr },
    { "SDL_strtol", (uintptr_t)&SDL_strtol },
    { "SDL_strtoll", (uintptr_t)&SDL_strtoll },
    { "_ZNKSt9exception4whatEv", (uintptr_t)&_ZNKSt9exception4whatEv },
    { "_ZNSt20bad_array_new_lengthC1Ev", (uintptr_t)&ov__ZNSt20bad_array_new_lengthC1Ev },
    { "_ZNSt20bad_array_new_lengthD1Ev", (uintptr_t)&_ZNSt20bad_array_new_lengthD1Ev },
    { "_ZNSt8bad_castC1Ev", (uintptr_t)&ov__ZNSt8bad_castC1Ev },
    { "_ZNSt8bad_castD1Ev", (uintptr_t)&_ZNSt8bad_castD1Ev },
    { "_ZNSt9bad_allocC1Ev", (uintptr_t)&ov__ZNSt9bad_allocC1Ev },
    { "_ZNSt9bad_allocD1Ev", (uintptr_t)&_ZNSt9bad_allocD1Ev },
    { "_ZNSt9exceptionD2Ev", (uintptr_t)&_ZNSt9exceptionD2Ev },
    { "_ZSt9terminatev", (uintptr_t)&_ZSt9terminatev },
    { "_ZTISt20bad_array_new_length", (uintptr_t)_ZTISt20bad_array_new_length },
    { "_ZTISt8bad_cast", (uintptr_t)_ZTISt8bad_cast },
    { "_ZTISt9bad_alloc", (uintptr_t)_ZTISt9bad_alloc },
    { "_ZTISt9exception", (uintptr_t)_ZTISt9exception },
    { "_ZTVN10__cxxabiv117__class_type_infoE", (uintptr_t)_ZTVN10__cxxabiv117__class_type_infoE },
    { "_ZTVN10__cxxabiv120__si_class_type_infoE", (uintptr_t)_ZTVN10__cxxabiv120__si_class_type_infoE },
    { "_ZTVN10__cxxabiv121__vmi_class_type_infoE", (uintptr_t)_ZTVN10__cxxabiv121__vmi_class_type_infoE },
    { "_ZdaPv", (uintptr_t)&_ZdaPv },
    { "_ZdaPvj", (uintptr_t)&_ZdaPvj },
    { "_ZdlPv", (uintptr_t)&_ZdlPv },
    { "_ZdlPvRKSt9nothrow_t", (uintptr_t)&_ZdlPvRKSt9nothrow_t },
    { "_ZdlPvj", (uintptr_t)&_ZdlPvj },
    { "_Znaj", (uintptr_t)&ov__Znaj },
    { "_ZnajRKSt9nothrow_t", (uintptr_t)&ov__ZnajRKSt9nothrow_t },
    { "_Znwj", (uintptr_t)&ov__Znwj },
    { "_ZnwjRKSt9nothrow_t", (uintptr_t)&ov__ZnwjRKSt9nothrow_t },
    { "__android_log_write", (uintptr_t)&ov___android_log_write },
    { "__ctype_get_mb_cur_max", (uintptr_t)&ov___ctype_get_mb_cur_max },
    { "__cxa_allocate_exception", (uintptr_t)&__cxa_allocate_exception },
    { "__cxa_atexit", (uintptr_t)&__cxa_atexit },
    { "__cxa_begin_catch", (uintptr_t)&__cxa_begin_catch },
    { "__cxa_current_primary_exception", (uintptr_t)&ov___cxa_current_primary_exception },
    { "__cxa_decrement_exception_refcount", (uintptr_t)&ov___cxa_decrement_exception_refcount },
    { "__cxa_end_catch", (uintptr_t)&__cxa_end_catch },
    { "__cxa_end_cleanup", (uintptr_t)&__cxa_end_cleanup },
    { "__cxa_finalize", (uintptr_t)&__cxa_finalize },
    { "__cxa_free_exception", (uintptr_t)&__cxa_free_exception },
    { "__cxa_increment_exception_refcount", (uintptr_t)&ov___cxa_increment_exception_refcount },
    { "__cxa_init_primary_exception", (uintptr_t)&__cxa_init_primary_exception },
    { "__cxa_pure_virtual", (uintptr_t)&__cxa_pure_virtual },
    { "__cxa_rethrow", (uintptr_t)&__cxa_rethrow },
    { "__cxa_rethrow_primary_exception", (uintptr_t)&ov___cxa_rethrow_primary_exception },
    { "__cxa_throw", (uintptr_t)&__cxa_throw },
    { "__cxa_uncaught_exceptions", (uintptr_t)&ov___cxa_uncaught_exceptions },
    { "__dynamic_cast", (uintptr_t)&__dynamic_cast },
    { "__emutls_get_address", (uintptr_t)&ov___emutls_get_address },
    { "__errno", (uintptr_t)&ov___errno },
    { "__gxx_personality_v0", (uintptr_t)&__gxx_personality_v0 },
    { "__memcpy_chk", (uintptr_t)&ov___memcpy_chk },
    { "__read_chk", (uintptr_t)&ov___read_chk },
    { "__sF", (uintptr_t)ov___sF },
    { "__stack_chk_fail", (uintptr_t)&ov___stack_chk_fail },
    { "__stack_chk_guard", (uintptr_t)ov___stack_chk_guard },
    { "__strcat_chk", (uintptr_t)&ov___strcat_chk },
    { "__strchr_chk", (uintptr_t)&ov___strchr_chk },
    { "__strcpy_chk", (uintptr_t)&ov___strcpy_chk },
    { "__strlen_chk", (uintptr_t)&ov___strlen_chk },
    { "__strncpy_chk", (uintptr_t)&ov___strncpy_chk },
    { "__vsnprintf_chk", (uintptr_t)&ov___vsnprintf_chk },
    { "__vsprintf_chk", (uintptr_t)&ov___vsprintf_chk },
    { "abort", (uintptr_t)&ov_abort },
    { "acos", (uintptr_t)&ov_acos },
    { "android_set_abort_message", (uintptr_t)&ov_android_set_abort_message },
    { "asctime", (uintptr_t)&ov_asctime },
    { "atan", (uintptr_t)&ov_atan },
    { "atof", (uintptr_t)&ov_atof },
    { "atoi", (uintptr_t)&atoi },
    { "atol", (uintptr_t)&atol },
    { "btowc", (uintptr_t)&btowc },
    { "calloc", (uintptr_t)&calloc },
    { "ceil", (uintptr_t)&ov_ceil },
    { "ceilf", (uintptr_t)&ov_ceilf },
    { "chdir", (uintptr_t)&ov_chdir },
    { "clock_gettime", (uintptr_t)&ov_clock_gettime },
    { "close", (uintptr_t)&ov_close },
    { "closedir", (uintptr_t)&ov_closedir },
    { "closelog", (uintptr_t)&ov_closelog },
    { "cos", (uintptr_t)&ov_cos },
    { "cosf", (uintptr_t)&ov_cosf },
    { "div", (uintptr_t)&div },
    { "exit", (uintptr_t)&ov_exit },
    { "exp", (uintptr_t)&ov_exp },
    { "exp2", (uintptr_t)&ov_exp2 },
    { "exp2f", (uintptr_t)&ov_exp2f },
    { "fchmod", (uintptr_t)&ov_fchmod },
    { "fchmodat", (uintptr_t)&ov_fchmodat },
    { "fclose", (uintptr_t)&ov_fclose },
    { "fdopen", (uintptr_t)&ov_fdopen },
    { "fdopendir", (uintptr_t)&ov_fdopendir },
    { "feof", (uintptr_t)&ov_feof },
    { "ferror", (uintptr_t)&ov_ferror },
    { "fflush", (uintptr_t)&ov_fflush },
    { "fgetc", (uintptr_t)&ov_fgetc },
    { "fgets", (uintptr_t)&ov_fgets },
    { "floor", (uintptr_t)&ov_floor },
    { "floorf", (uintptr_t)&ov_floorf },
    { "fopen", (uintptr_t)&ov_fopen },
    { "fprintf", (uintptr_t)&ov_fprintf },
    { "fputc", (uintptr_t)&ov_fputc },
    { "fputs", (uintptr_t)&ov_fputs },
    { "fputwc", (uintptr_t)&ov_fputwc },
    { "fread", (uintptr_t)&ov_fread },
    { "free", (uintptr_t)&free },
    { "freelocale", (uintptr_t)&ov_freelocale },
    { "frexp", (uintptr_t)&ov_frexp },
    { "fscanf", (uintptr_t)&ov_fscanf },
    { "fseek", (uintptr_t)&ov_fseek },
    { "fseeko", (uintptr_t)&ov_fseeko },
    { "fstat", (uintptr_t)&ov_fstat },
    { "ftell", (uintptr_t)&ov_ftell },
    { "ftello", (uintptr_t)&ov_ftello },
    { "ftruncate", (uintptr_t)&ov_ftruncate },
    { "fwrite", (uintptr_t)&ov_fwrite },
    { "getc", (uintptr_t)&ov_getc },
    { "getcwd", (uintptr_t)&ov_getcwd },
    { "getenv", (uintptr_t)&getenv },
    { "getwc", (uintptr_t)&ov_getwc },
    { "gmtime", (uintptr_t)&ov_gmtime },
    { "hypot", (uintptr_t)&ov_hypot },
    { "ioctl", (uintptr_t)&ov_ioctl },
    { "iswalpha_l", (uintptr_t)&ov_iswalpha_l },
    { "iswblank_l", (uintptr_t)&ov_iswblank_l },
    { "iswcntrl_l", (uintptr_t)&ov_iswcntrl_l },
    { "iswdigit_l", (uintptr_t)&ov_iswdigit_l },
    { "iswlower_l", (uintptr_t)&ov_iswlower_l },
    { "iswprint_l", (uintptr_t)&ov_iswprint_l },
    { "iswpunct_l", (uintptr_t)&ov_iswpunct_l },
    { "iswspace_l", (uintptr_t)&ov_iswspace_l },
    { "iswupper_l", (uintptr_t)&ov_iswupper_l },
    { "iswxdigit_l", (uintptr_t)&ov_iswxdigit_l },
    { "ldexp", (uintptr_t)&ov_ldexp },
    { "link", (uintptr_t)&ov_link },
    { "localeconv", (uintptr_t)&localeconv },
    { "localtime64_r", (uintptr_t)&ov_localtime64_r },
    { "log", (uintptr_t)&ov_log },
    { "log10", (uintptr_t)&ov_log10 },
    { "log10f", (uintptr_t)&ov_log10f },
    { "log2", (uintptr_t)&ov_log2 },
    { "logf", (uintptr_t)&ov_logf },
    { "longjmp", (uintptr_t)&longjmp },
    { "lseek", (uintptr_t)&ov_lseek },
    { "lseek64", (uintptr_t)&ov_lseek64 },
    { "lstat", (uintptr_t)&ov_lstat },
    { "malloc", (uintptr_t)&ov_malloc },
    { "mbrlen", (uintptr_t)&mbrlen },
    { "mbrtowc", (uintptr_t)&mbrtowc },
    { "mbsnrtowcs", (uintptr_t)&mbsnrtowcs },
    { "mbsrtowcs", (uintptr_t)&mbsrtowcs },
    { "mbtowc", (uintptr_t)&mbtowc },
    { "memchr", (uintptr_t)&memchr },
    { "memcmp", (uintptr_t)&memcmp },
    { "memcpy", (uintptr_t)&memcpy },
    { "memmove", (uintptr_t)&memmove },
    { "memset", (uintptr_t)&memset },
    { "mkdir", (uintptr_t)&ov_mkdir },
    { "modf", (uintptr_t)&ov_modf },
    { "nanosleep", (uintptr_t)&ov_nanosleep },
    { "newlocale", (uintptr_t)&ov_newlocale },
    { "open", (uintptr_t)&ov_open },
    { "openat", (uintptr_t)&ov_openat },
    { "opendir", (uintptr_t)&ov_opendir },
    { "openlog", (uintptr_t)&ov_openlog },
    { "pathconf", (uintptr_t)&ov_pathconf },
    { "pow", (uintptr_t)&ov_pow },
    { "powf", (uintptr_t)&ov_powf },
    { "pthread_cond_broadcast", (uintptr_t)&ov_pthread_cond_broadcast },
    { "pthread_cond_destroy", (uintptr_t)&ov_pthread_cond_destroy },
    { "pthread_cond_signal", (uintptr_t)&ov_pthread_cond_signal },
    { "pthread_cond_timedwait", (uintptr_t)&ov_pthread_cond_timedwait },
    { "pthread_cond_wait", (uintptr_t)&ov_pthread_cond_wait },
    { "pthread_create", (uintptr_t)&ov_pthread_create },
    { "pthread_detach", (uintptr_t)&ov_pthread_detach },
    { "pthread_getspecific", (uintptr_t)&ov_pthread_getspecific },
    { "pthread_join", (uintptr_t)&ov_pthread_join },
    { "pthread_key_create", (uintptr_t)&ov_pthread_key_create },
    { "pthread_mutex_destroy", (uintptr_t)&ov_pthread_mutex_destroy },
    { "pthread_mutex_init", (uintptr_t)&ov_pthread_mutex_init },
    { "pthread_mutex_lock", (uintptr_t)&ov_pthread_mutex_lock },
    { "pthread_mutex_trylock", (uintptr_t)&ov_pthread_mutex_trylock },
    { "pthread_mutex_unlock", (uintptr_t)&ov_pthread_mutex_unlock },
    { "pthread_mutexattr_destroy", (uintptr_t)&ov_pthread_mutexattr_destroy },
    { "pthread_mutexattr_init", (uintptr_t)&ov_pthread_mutexattr_init },
    { "pthread_mutexattr_settype", (uintptr_t)&ov_pthread_mutexattr_settype },
    { "pthread_self", (uintptr_t)&ov_pthread_self },
    { "pthread_setspecific", (uintptr_t)&ov_pthread_setspecific },
    { "qsort", (uintptr_t)&qsort },
    { "rand", (uintptr_t)&rand },
    { "read", (uintptr_t)&ov_read },
    { "readdir", (uintptr_t)&ov_readdir },
    { "readlink", (uintptr_t)&ov_readlink },
    { "realloc", (uintptr_t)&realloc },
    { "realpath", (uintptr_t)&ov_realpath },
    { "remove", (uintptr_t)&ov_remove },
    { "rename", (uintptr_t)&ov_rename },
    { "rint", (uintptr_t)&ov_rint },
    { "rintf", (uintptr_t)&ov_rintf },
    { "round", (uintptr_t)&ov_round },
    { "roundf", (uintptr_t)&ov_roundf },
    { "sendfile", (uintptr_t)&ov_sendfile },
    { "setbuf", (uintptr_t)&ov_setbuf },
    { "setjmp", (uintptr_t)&setjmp },
    { "setlocale", (uintptr_t)&setlocale },
    { "sigaction", (uintptr_t)&ov_sigaction },
    { "sigemptyset", (uintptr_t)&ov_sigemptyset },
    { "siglongjmp", (uintptr_t)&longjmp },
    { "sigsetjmp", (uintptr_t)&setjmp },
    { "sin", (uintptr_t)&ov_sin },
    { "sincos", (uintptr_t)&ov_sincos },
    { "sincosf", (uintptr_t)&ov_sincosf },
    { "sinf", (uintptr_t)&ov_sinf },
    { "sinhf", (uintptr_t)&ov_sinhf },
    { "snprintf", (uintptr_t)&snprintf },
    { "srand", (uintptr_t)&srand },
    { "sscanf", (uintptr_t)&sscanf },
    { "stat", (uintptr_t)&ov_stat },
    { "statvfs", (uintptr_t)&ov_statvfs },
    { "strcasecmp", (uintptr_t)&strcasecmp },
    { "strcat", (uintptr_t)&strcat },
    { "strchr", (uintptr_t)&strchr },
    { "strcmp", (uintptr_t)&strcmp },
    { "strcoll_l", (uintptr_t)&ov_strcoll_l },
    { "strcpy", (uintptr_t)&strcpy },
    { "strerror", (uintptr_t)&strerror },
    { "strerror_r", (uintptr_t)&ov_strerror_r },
    { "strftime", (uintptr_t)&ov_strftime },
    { "strftime_l", (uintptr_t)&ov_strftime_l },
    { "strlen", (uintptr_t)&strlen },
    { "strncasecmp", (uintptr_t)&strncasecmp },
    { "strncmp", (uintptr_t)&strncmp },
    { "strncpy", (uintptr_t)&strncpy },
    { "strsep", (uintptr_t)&strsep },
    { "strtod", (uintptr_t)&ov_strtod },
    { "strtof", (uintptr_t)&ov_strtof },
    { "strtok", (uintptr_t)&strtok },
    { "strtol", (uintptr_t)&strtol },
    { "strtold", (uintptr_t)&ov_strtold },
    { "strtold_l", (uintptr_t)&ov_strtold_l },
    { "strtoll", (uintptr_t)&strtoll },
    { "strtoll_l", (uintptr_t)&ov_strtoll_l },
    { "strtoul", (uintptr_t)&strtoul },
    { "strtoull", (uintptr_t)&strtoull },
    { "strtoull_l", (uintptr_t)&ov_strtoull_l },
    { "strxfrm_l", (uintptr_t)&ov_strxfrm_l },
    { "swprintf", (uintptr_t)&swprintf },
    { "symlink", (uintptr_t)&ov_symlink },
    { "sysconf", (uintptr_t)&ov_sysconf },
    { "syslog", (uintptr_t)&ov_syslog },
    { "tan", (uintptr_t)&ov_tan },
    { "tanf", (uintptr_t)&ov_tanf },
    { "towlower_l", (uintptr_t)&ov_towlower_l },
    { "towupper_l", (uintptr_t)&ov_towupper_l },
    { "truncate", (uintptr_t)&ov_truncate },
    { "ungetc", (uintptr_t)&ov_ungetc },
    { "ungetwc", (uintptr_t)&ov_ungetwc },
    { "unlinkat", (uintptr_t)&ov_unlinkat },
    { "uselocale", (uintptr_t)&ov_uselocale },
    { "utimensat", (uintptr_t)&ov_utimensat },
    { "vasprintf", (uintptr_t)&vasprintf },
    { "vfprintf", (uintptr_t)&ov_vfprintf },
    { "vsnprintf", (uintptr_t)&vsnprintf },
    { "vsscanf", (uintptr_t)&vsscanf },
    { "wcrtomb", (uintptr_t)&wcrtomb },
    { "wcscoll_l", (uintptr_t)&ov_wcscoll_l },
    { "wcslen", (uintptr_t)&wcslen },
    { "wcsnrtombs", (uintptr_t)&wcsnrtombs },
    { "wcstod", (uintptr_t)&ov_wcstod },
    { "wcstof", (uintptr_t)&ov_wcstof },
    { "wcstol", (uintptr_t)&wcstol },
    { "wcstold", (uintptr_t)&ov_wcstold },
    { "wcstoll", (uintptr_t)&wcstoll },
    { "wcstoul", (uintptr_t)&wcstoul },
    { "wcstoull", (uintptr_t)&wcstoull },
    { "wcsxfrm_l", (uintptr_t)&ov_wcsxfrm_l },
    { "wctob", (uintptr_t)&wctob },
    { "wmemchr", (uintptr_t)&wmemchr },
    { "wmemcmp", (uintptr_t)&wmemcmp },
    { "write", (uintptr_t)&write },
};
const size_t g_imports_count = sizeof g_imports / sizeof g_imports[0];
